trigger:
- master

pool: 
  name: TwinCAT-Builds

variables:
  Version.Major: '1'
  Version.Minor: '0'
  Version.CounterName: Version$(Version.Major).$(Version.Minor)
  Version.Build: $[counter(variables['Version.CounterName'], 0)]

name: TcOpcUaSamples_v$(Version.Major).$(Version.Minor).$(Version.Build)($(Rev:r)).$(Build.SourceBranchName)

steps:
- task: CopyFiles@1
  displayName: 'Copying files to ArtifactStagingDirectory'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))
  displayName: 'Publish build artifacts to pipeline'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: TcOpcUaSamples
    publishLocation: 'Container'
