<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{fc8ad144-f214-4b14-b487-cf23eecee195}" SpecialFunc="None">
    <Declaration><![CDATA[(* Demonstrates how to use the TwinCAT OPC UA Client with PLCopen function blocks. Please make sure to configure server settings in GVL Settings. *)
PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_CONNECT(); // Call sample for UA_Connect and UA_Disconnect
//PRG_CONNECT_Secure(); // Call sample for UA_Connect with security and UA_Disconnect
//PRG_GETSTATUS(); // Call sample to query server connection status via UA_ConnectGetStatus
//PRG_BROWSE(); // Call sample for UA_Browse
//PRG_READ(); // Call sample for UA_Read
//PRG_READ_IndexRange(); // Call sample for UA_Read
//PRG_READ_List(); // Call sample for UA_ReadList
//PRG_READ_List_Array(); // Call sample for UA_ReadList to read array elements
//PRG_WRITE(); // Call sample for UA_Write
//PRG_WRITE_IndexRange(); // Call sample for UA_Write
//PRG_METHOD(); // Call sample for UA_MethodCall
//PRG_METHOD_NOARGS(); // Call sample for UA_MethodCall without input or output arguments]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>