<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MAIN" Id="{3b66bfef-7a47-4837-bb7c-ec115028f14d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	i : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[i := i + 1;

PRG_HA_SingleNode();	// call sample for UA_HistoryUpdate
PRG_HA_MultipleNodes();	// call sample for UA_HistoryUpdate with multiple nodes
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="42" Count="0" />
      <LineId Id="68" Count="0" />
      <LineId Id="66" Count="1" />
      <LineId Id="73" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>