networks:
  container-network:
    name: container-network
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    hostname: mosquitto
    ports:
      - "1883:1883"
    restart: unless-stopped
    volumes:
      - ./simple-mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      container-network:
        ipv4_address: 192.168.20.2

  server:
    image: open62541/open62541:master
    container_name: server
    hostname: server
    ports:
      - "4840:4840"
    restart: unless-stopped
    networks:
      container-network:
        ipv4_address: 192.168.20.4

  tc31-opc-ua-client:
    image: tc31-opc-ua-clientpubsub:latest
    container_name: tc31-opc-ua-clientpubsub
    hostname: tc31-opc-ua-clientpubsub
    restart: unless-stopped
    depends_on:
      - mosquitto
    privileged: true
    volumes:
      - /dev/hugepages:/dev/hugepages:rw
    networks:
      container-network:
        ipv4_address: 192.168.20.3
    environment:
      - AMS_NETID=15.15.15.15.1.1
